### ISSUE TITLE
Failed to resize matrix, rows and cols == zero!

### ISSUE THREAD

**Issue by JairoJs** [nickgillian/grt#84]
Hello, sorry to bother. Im getting that error when I try to train an HMM continous model. Any Idea of what might be causing it? I could get to train it with a smaller data set. but with the original size one it throws that error. the data set its 36 dimensions and has 842 training examples and 8 clases, its 15Mbytes.... A DTW model have been train with no errors with this data set

**Comment by JairoJs** [comment]
I need some guidance here. the thing is if I change de downsample value to 5 it doesnt give the error but prediction acuracy drops from 86 % to 0! if I change it to 6 or more it gives that error

**Comment by nickgillian** [comment]
It sounds like there is either a bug in the downsample function, or you are trying to downsample the data with a downsample value that is greater than the original timeseries.

Can you confirm the rough length of your timeseries data?  You mentioned 36 dimensions above, with 842 training examples.  How long (in time) is each gesture?

**Comment by nickgillian** [comment]
I think I might have found the possible issue, if you set the downsampleFactor so it is greater than the length of the timeseries, then this caused the size of the downsampled matrix to have zero rows.

I've just pushed a fix for this to both the master and dev branches for version GRT 0.2.1.

I hope this fixes the issue.

**Comment by JairoJs** [comment]
Hello it did fix it partialy, I am still getting the erro but with higer downsample values like 10, but I could get to train the model fine with a value of 7, the rouh length of the gestures are 45 - 50 rows for each timeSeries
